name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  CLIENT_IMAGE_NAME: gainzville
  SERVER_IMAGE_NAME: gainzville-server

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build client image
        run: docker build . --file Dockerfile --tag $CLIENT_IMAGE_NAME

      - name: Build server image
        run: docker build . --file DockerfileServer --tag $SERVER_IMAGE_NAME
