name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - deployment

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  DROPLET_NAME: gainzville1
  CLIENT_IMAGE_NAME: gainzville
  SERVER_IMAGE_NAME: gainzville-server

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build client image
        run: docker build . --file Dockerfile --tag $CLIENT_IMAGE_NAME

      - name: Build server image
        run: docker build . --file DockerfileServer --tag $SERVER_IMAGE_NAME
                
      - name: Clean client container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker ps -q --filter "name=${CLIENT_IMAGE_NAME}" | grep -q . && docker stop ${CLIENT_IMAGE_NAME} && docker rm -fv ${CLIENT_IMAGE_NAME} && docker rmi -f ${CLIENT_IMAGE_NAME}
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          privateKey: ${{ secrets.DROPLET_PRIVATE }}
    
      - name: Clean server container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker ps -q --filter "name=${SERVER_IMAGE_NAME}" | grep -q . && docker stop ${SERVER_IMAGE_NAME} && docker rm -fv ${SERVER_IMAGE_NAME} && docker rmi -f ${SERVER_IMAGE_NAME}
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          privateKey: ${{ secrets.DROPLET_PRIVATE }}
        
      - name: Push client image
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${CLIENT_IMAGE_NAME}
        
      - name: Push server image
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${SERVER_IMAGE_NAME}
          
      - name: Pull client image
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker pull docker.pkg.github.com/gainz-ville/gainzville/${CLIENT_IMAGE_NAME}
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          privateKey: ${{ secrets.DROPLET_PRIVATE }}
    
      - name: Pull server image
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker pull docker.pkg.github.com/gainz-ville/gainzville/${SERVER_IMAGE_NAME}
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          privateKey: ${{ secrets.DROPLET_PRIVATE }}

      - name: Run client container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker run --name ${CLIENT_IMAGE_NAME} -p 80:80 -d ${CLIENT_IMAGE_NAME}
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          privateKey: ${{ secrets.DROPLET_PRIVATE }}
    
      - name: Run server container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker run --name ${SERVER_IMAGE_NAME} -p 5050:80 -d ${SERVER_IMAGE_NAME}
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          privateKey: ${{ secrets.DROPLET_PRIVATE }}
      
      

          
